import Navbar from "@repo/components/Navbar";
import { theme } from "@repo/theme";
import { Container, CssBaseline, ThemeProvider } from "@mui/material";
import { Player } from "@repo/components/Player";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryProvider } from "@repo/providers/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <QueryProvider>
          {/*<ThemeProvider>*/}
          {/*  <CssBaseline />*/}
            <Navbar />
            <Container style={{ margin: "90px" }}>{children}</Container>
            <Player />
          {/*</ThemeProvider>*/}
        </QueryProvider>
      </body>
    </html>
  );
}
